service: portfolio

image: israelaraujo70/portfolio-3

servers:
  web:
    hosts:
      - <%= ENV["KAMAL_HOST"] || "YOUR_SERVER_IP" %>
    options:
      volume:
        - portfolio_data:/app/data

proxy:
  ssl: false
  host: portfolio.israeldeveloper.com.br
  app_port: 3000
  healthcheck:
    path: /

registry:
  server: ghcr.io
  username: IsraelAraujo70
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64

env:
  clear:
    NODE_ENV: production
    NEXT_TELEMETRY_DISABLED: 1
    DATABASE_PATH: /app/data/notes.db
  secret:
    - OPENROUTER_API_KEY
    - OPENROUTER_MODEL

ssh:
  user: <%= ENV["KAMAL_SSH_USER"] || "baremetal" %>
